CREATE TABLE IF NOT EXISTS app_role(
    id BIGINT(19) AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255),
    role_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;